# Generated by Django 6.0.2 on 2026-03-08 11:14

import django.db.models.deletion
import my_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        default=my_auth.models.generate_short_code,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_link",
                        to="my_auth.form",
                    ),
                ),
            ],
        ),
    ]
