# Generated by Django 6.0.2 on 2026-03-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0002_shortlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="time_taken",
            field=models.FloatField(default=0.0),
        ),
    ]
